### ISSUE TITLE
Error-reporting pattern does not seem to work

### ISSUE THREAD

**Issue by bluss** [DanielKeep/rust-custom-derive#30]
I'm mainly here because I wanted to look up and copy the error reporting pattern here

https://github.com/DanielKeep/rust-custom-derive/blob/1252f258cdb9b7c9867f937c52c2f5c0e69a9c03/tests/enum_try_from.rs#L56-L61

but it does not seem to work in modern Rust; the error message does not mention the string at all.

Do you know any good way to report syntax errors in macros? Something like this seems tempting to put in the appropriate fallback branch for a macro:

```rust
struct IndexParameterMustBeFirstError;
const _error: () = IndexParameterMustBeFirstError;
```

**Comment by DanielKeep** [comment]
Hey, going through the back log.

Yeah, this used to work much better when the compiler actually showed the macro code itself, rather than just the top level.  That said, the `concat!` thing *never* worked.  I think I just forgot to actually replace it with something more coherent since, y'know, you can't test compile failures easily.

Anyway, I found another way of doing this:

```rust
macro_rules! enum_derive_error {
    (@item $msg:tt) => {
        const $msg: () = ();
    };
}
```

This generates error messages like the following on 1.19.0 (and also works at least as far back as 1.2.0):

```text
error: expected identifier, found `"oh no."`
 --> C:\Users\drk\AppData\Local\Cargo\script-cache\file-error-38ae6ede6856098c\error.rs:9:26
  |
9 | enum_derive_error!{@item "oh no."}
  |                          ^^^^^^^^
```

The macro can be `cfg`'d out and replaced with a version that invokes `compile_error!` in 1.20.0 or higher, giving:

```text
error: expected identifier, found `"oh no."`
 --> C:\Users\drk\AppData\Local\Cargo\script-cache\file-error-38ae6ede6856098c\error.rs:9:26
  |
9 | enum_derive_error!{@item "oh no."}
  |                          ^^^^^^^^
```

The major problem with this is that you *need* a separate macro for this, *and* you need to add a build script for version detection.  That *also* means (probably) depending on the `semver` and `rustc_version` crates.

This trick is only used in two places in these crates: in `enum_derive_util!` for parsing unitary things, and in a test.  As such, I'm probably just going to use the simpler "replace an identifier" trick and not bother with `compile_error!` until it's at least more broadly available, or until there's a half decent way to handle version detection.

**Comment by bluss** [comment]
There's a simpler version checker crate at least, version check or something like that by the rocket author

**Comment by bluss** [comment]
Thanks for the tips and the reminder -- I had for got about compile_error. The simple version check crate is [version_check](https://crates.io/crates/version_check), it's got a compile time in my taste. (Thanks @SergioBenitez!)

**Comment by DanielKeep** [comment]
Oh, nice!  I'm all for removing dependencies.  It's less convenient to use (`is_min_version` returns an `Option<(bool, String)>` for some inexplicable reason), but dropping compile times should be worth it.

**Comment by DanielKeep** [comment]
Note to self: removed version_check as a dependency because it breaks on 1.3 and 1.4, but not 1.2.  "invalid tar archive" when trying to run Cargo.  A [known bug in Cargo](https://github.com/rust-lang/cargo/issues/4143), but doesn't seem to be any interest in fixing it.
